// //hasOwnProperty is a method that checks if a property exists directly on the object itself, not in its prototype chain

// const Animal={
//     name:"Domy"
// };

// console.log(Animal.hasOwnProperty("name"));

// //this gives output as true because "name" → exists on animal itself → true

// const Pet={
//     name:"Domy"
// };

// console.log(Pet.hasOwnProperty("toString"));

// //this gives false as output because "toString" → exists in Object.prototype → false